spring:
  application:
    name: shortener
  datasource:
    jdbc-url: jdbc:h2:mem:shortener
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**

server:
  port: 8888
  tomcat:
    use-relative-redirects: true
